services:
  db:
    image: postgres:15 # Use a specific version of the official Postgres image
    container_name: webhook_db # Give the container a specific name
    environment:
      POSTGRES_USER: postgres # Username used in your DATABASE_URL
      POSTGRES_PASSWORD: postgres # Password used in your DATABASE_URL
      POSTGRES_DB: webhook_svc # Database name used in your DATABASE_URL
    ports:
      - "5432:5432" # Map port 5432 on your host to port 5432 in the container
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist database data using a named volume

volumes:
  postgres_data: {} # Define the named volume for data persistence
